name: syntax
on: push
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Checker owner    
        run: echo Checker made by Popescu David
      - name: compiling
        run: gcc -v 
      - run:  |
               if [ "$(python sum.py 4 7)" != "13" ]
               then
                   exit 1
               fi

                
